/* The exercise library.
   Descriptions, instructions and cues are general-population technique
   guidance, not personalized programming. Set/rep prescriptions are
   conservative STARTING POINTS — the progression rules in Part Four are what
   actually move them. Swap this array for your own movements; every other
   module reads it and nothing else. */
export const CATEGORIES = [
  { slug: "lower", name: "Lower body" },
  { slug: "push", name: "Upper push" },
  { slug: "pull", name: "Upper pull" },
  { slug: "core", name: "Core & carries" },
  { slug: "power", name: "Power & elastic" },
  { slug: "cardio", name: "Conditioning" },
  { slug: "mobility", name: "Mobility & tissue" },
];

/* The four traditions this library borrows from. Each exercise is tagged with
   the schools that actually program it, so the filters in Part Three and the
   week variants in Part Five can both read from the same tags. */
export const SCHOOLS = [
  {
    slug: "strength",
    name: "Starting Strength",
    lineage: "Mark Rippetoe",
    color: "#7c9eff",
    thesis:
      "A handful of barbell lifts, done heavy, added to a little at a time. Rippetoe's argument is that whole-body barbell movements through a full range of motion are the most efficient way to make a novice stronger — and that a novice can add weight to the bar every single session for months before anything cleverer is needed.",
    signature: [
      "Squat, press, deadlift, bench press, power clean — that's most of it",
      "Linear progression: add the smallest plate every session until it stops working",
      "Sets of five, three work sets, long rests",
      "Technique taught as a model, not a feeling",
    ],
    bestAt: "Getting a beginner genuinely strong in the shortest calendar time.",
    blindSpot:
      "Little conditioning, little single-leg or elastic work, and the linear phase does eventually end — after which the programming has to change.",
  },
  {
    slug: "kettlebell",
    name: "Hardstyle kettlebell",
    lineage: "Pavel Tsatsouline · StrongFirst",
    color: "#ff9e7c",
    thesis:
      "Strength as a skill you practise rather than a workout you survive. Pavel's hardstyle approach treats tension as the technique — maximal contraction, sharp breathing, crisp reps — and builds programs from very few movements done very well, most famously the swing and the get-up.",
    signature: [
      "The swing and the Turkish get-up as a near-complete program (Simple & Sinister)",
      "Practice, don't exhaust: stop well short of failure, most days",
      "\u2018Grease the groove\u2019 — frequent, easy, high-quality sets",
      "Power breathing and full-body tension on every rep",
    ],
    bestAt: "Hip power, grip, shoulder stability and conditioning from minimal equipment.",
    blindSpot:
      "Ballistics alone won't maximise muscle size, and the loading jumps between bells are coarse compared with plates.",
  },
  {
    slug: "metcon",
    name: "Box conditioning",
    lineage: "CrossFit · BoxLife",
    color: "#ffd27c",
    thesis:
      "Constantly varied functional movement at high intensity, scored against the clock. The box model mixes weightlifting, gymnastics and monostructural cardio into short conditioning pieces — AMRAPs, EMOMs, for-time couplets — and the score is what makes people push.",
    signature: [
      "AMRAP: as many rounds as possible in a fixed window",
      "EMOM: every minute on the minute, a set amount of work",
      "For time: a fixed amount of work, done as fast as form allows",
      "Everything scales — the stimulus is the constant, the load is not",
    ],
    bestAt: "Work capacity, and the motivation that comes from a measurable score.",
    blindSpot:
      "Technical lifts under fatigue is where injuries cluster. Intensity has to be earned with technique first, and scaled honestly.",
  },
  {
    slug: "fascia",
    name: "Fascial elasticity",
    lineage: "Thomas Myers · fascia training research",
    color: "#7cffb2",
    thesis:
      "Connective tissue is a load-bearing, elastic network, not packing material. Fascia-oriented training loads it the way it's built to be loaded — springy rebounds, long-lever stretches under tension, and multi-directional movement — on the argument that tendon and fascial stiffness is what makes movement efficient and remodels slowly, over months.",
    signature: [
      "Elastic bounce: short ground contacts, rebound rather than grind",
      "Loaded stretch: strength through the longest range, held under tension",
      "Multi-directional and rotational work, not just sagittal-plane lifts",
      "Long timescales — collagen remodels over 6-24 months, not weeks",
    ],
    bestAt: "Movement efficiency, tendon resilience, and ranges that pure barbell work never visits.",
    blindSpot:
      "The evidence base is thinner and younger than the strength literature. Treat the mechanisms as plausible and the claims as provisional.",
  },
];

export const EXERCISES = [
  {
    name: "Goblet squat",
    schools: ["kettlebell"],
    category: "lower",
    equipment: "One dumbbell or kettlebell",
    bodyweight: false,
    level: "Beginner",
    focus: "Quads, glutes, upper back, trunk",
    prescription: "3 sets × 8-12 reps",
    why:
      "The most forgiving loaded squat there is. Holding the weight at your chest counterweights you, which keeps the torso upright and lets most people reach real depth on day one — with a load light enough that a bad rep is a nuisance, not an injury.",
    steps: [
      "Hold a dumbbell vertically against your chest, cupping the top head with both hands, elbows tucked under it.",
      "Stand with your feet a little wider than your hips, toes turned out 15-30°.",
      "Take a breath into your belly and brace as if you were about to be poked in the stomach.",
      "Sit down between your feet — hips and knees bending together — keeping your chest tall and your whole foot on the floor.",
      "Descend until your thighs are roughly parallel to the floor, or as deep as you can go without your lower back rounding.",
      "Drive through the middle of your foot to stand, squeezing your glutes at the top. Breathe out at the top, not the bottom.",
    ],
    cues: [
      "Knees travelling forward over the toes is normal and fine; knees collapsing inward is not — push them out toward your little toes.",
      "If your heels lift, your ankles are limiting you: elevate the heels ~1cm on small plates while you work on ankle mobility.",
      "The elbows should stay inside the knees at the bottom. If they're outside, your stance is too narrow.",
    ],
  },
  {
    name: "Romanian deadlift",
    schools: ["strength"],
    category: "lower",
    equipment: "Dumbbells or a barbell",
    bodyweight: false,
    level: "Intermediate",
    focus: "Hamstrings, glutes, spinal erectors",
    prescription: "3 sets × 6-10 reps",
    why:
      "The hip hinge, loaded. Trains the back of the body through a long stretch, which is where hamstrings do most of their growing — and teaches the pattern you actually want when you pick something up off the floor.",
    steps: [
      "Stand holding the weights in front of your thighs, feet hip-width apart, knees softly unlocked.",
      "Pull your shoulders back and down so the bar or dumbbells rest against your legs.",
      "Push your hips straight back — not down — letting the weights slide down your thighs, staying in contact the whole way.",
      "Keep your back flat and your shins near vertical. Stop when you feel a strong hamstring stretch, usually just below the knee.",
      "Reverse it by driving your hips forward, standing tall with a glute squeeze at the top rather than leaning back.",
    ],
    cues: [
      "This is a hinge, not a squat: if your knees are bending a lot, you're squatting the weight down.",
      "Range of motion is set by your hamstrings, not by the floor. Touching the ground with a rounded back is a worse rep, not a bigger one.",
      "Let the weight drift away from your legs and your lower back takes the load. Keep it grazing you.",
    ],
  },
  {
    name: "Split squat",
    schools: [],
    category: "lower",
    equipment: "Bodyweight, or dumbbells to progress",
    bodyweight: true,
    level: "Beginner",
    focus: "Quads, glutes, single-leg balance",
    prescription: "3 sets × 8-12 reps per leg",
    why:
      "One leg at a time, which exposes and then fixes the side-to-side difference a two-legged squat hides. It also loads the hip stabilisers hard while asking very little of your lower back.",
    steps: [
      "Step one foot forward into a long stride — long enough that both knees can bend to about 90°.",
      "Keep your front foot flat and your back heel lifted, weight on the ball of the back foot.",
      "Stand tall, brace your trunk, and lower straight down until your back knee is a few centimetres off the floor.",
      "Drive through the front heel to stand back up, keeping the stride length unchanged.",
      "Finish all the reps on one side before switching, and start the next set with the weaker leg.",
    ],
    cues: [
      "Down, not forward. If your front knee shoots way past your toes, your stride is too short.",
      "Front shin roughly vertical loads the glutes more; a more forward shin loads the quads more. Both are legitimate — pick one and be consistent.",
      "Wobbling side to side means the stance is too narrow: set your feet on two parallel lines, not a tightrope.",
    ],
  },
  {
    name: "Hip thrust",
    schools: [],
    category: "lower",
    equipment: "A bench; barbell or dumbbell to load",
    bodyweight: true,
    level: "Beginner",
    focus: "Glutes, hamstrings",
    prescription: "3 sets × 10-15 reps",
    why:
      "Peak load exactly where the glutes are shortest, which is the part of the range a squat barely touches. Start with the floor version (glute bridge) and move to a bench when the top position gets easy.",
    steps: [
      "Sit on the floor with your upper back against the long edge of a bench, knees bent, feet flat and hip-width apart.",
      "If loading, rest the weight across your hips — use a pad or folded towel.",
      "Tuck your chin slightly and keep your ribs down; look at a point on the wall a few metres ahead.",
      "Drive through your heels and push your hips up until your torso and thighs form a straight line.",
      "Squeeze the glutes hard for a full second at the top, then lower under control until your hips are just off the floor.",
    ],
    cues: [
      "The finish is a straight line, not an arch. If you feel it in your lower back, you've gone past the top — squeeze the glutes and stop there.",
      "Shins should be roughly vertical at the top. Feet too close makes it a quad exercise; too far makes it a hamstring one.",
      "Drive through the heels, not the toes.",
    ],
  },
  {
    name: "Push-up",
    schools: ["metcon"],
    category: "push",
    equipment: "None",
    bodyweight: true,
    level: "Beginner",
    focus: "Chest, triceps, front delts, trunk",
    prescription: "3 sets × 6-15 reps",
    why:
      "A moving plank as much as a pressing exercise — the trunk has to hold a straight line while the arms work. Scales infinitely: hands elevated to make it easier, feet elevated or a pause added to make it harder.",
    steps: [
      "Set your hands slightly wider than your shoulders, fingers pointing forward, directly under your chest.",
      "Extend your legs behind you, feet hip-width. Squeeze your glutes and brace your abs so your body forms one straight line.",
      "Lower yourself under control until your chest is a fist's height from the floor, elbows tracking back at about 45° from your ribs.",
      "Keep your neck long — the head moves with the spine, it doesn't lead.",
      "Push the floor away until your elbows are straight, letting your shoulder blades spread apart at the top.",
    ],
    cues: [
      "Hips sagging or piking up is the trunk quitting before the arms do. Regress to hands on a bench and keep the line.",
      "Elbows flared straight out to the sides puts the shoulder in its most vulnerable position. Aim for an arrow shape, not a T.",
      "Full lockout at the top, chest low at the bottom. Half reps in the middle are the least useful part of the range.",
    ],
  },
  {
    name: "Dumbbell bench press",
    schools: [],
    category: "push",
    equipment: "Two dumbbells and a bench",
    bodyweight: false,
    level: "Beginner",
    focus: "Chest, triceps, front delts",
    prescription: "3 sets × 8-12 reps",
    why:
      "Dumbbells let each arm move on its own path and travel deeper than a bar allows, and they're far easier to bail out of when a set goes wrong. This is the horizontal press to build first.",
    steps: [
      "Sit on the bench with the dumbbells on your thighs, then lie back, using your knees to kick them into position over your chest.",
      "Plant your feet, pull your shoulder blades back and down into the bench, and keep them pinned there for every rep.",
      "Start with arms extended, weights above your lower chest, palms facing forward or slightly turned in.",
      "Lower until the dumbbells are level with your chest and you feel a stretch across it — elbows about 45° from your torso.",
      "Press back up and slightly together, stopping just short of clashing the weights.",
      "To finish the set, bring the dumbbells to your chest, tuck your chin, and sit up with them on your thighs.",
    ],
    cues: [
      "Shoulder blades stay retracted the whole set — pressing off loose shoulders is where most bench shoulder pain starts.",
      "Wrists stacked over elbows, not bent back.",
      "Don't bounce the weights off your chest. If you need momentum to start the rep, the load is too heavy.",
    ],
  },
  {
    name: "Overhead press",
    schools: ["strength", "kettlebell"],
    category: "push",
    equipment: "Dumbbells or a barbell",
    bodyweight: false,
    level: "Intermediate",
    focus: "Shoulders, triceps, upper back, trunk",
    prescription: "3 sets × 6-10 reps",
    why:
      "The most honest test of pressing strength: nothing to lie on, so the trunk and hips have to hold the base while the shoulders work. It also builds the overhead range of motion most desk-bound shoulders slowly lose.",
    steps: [
      "Stand with feet hip-width, weights racked at shoulder height, palms facing forward, elbows slightly in front of the bar or dumbbells.",
      "Squeeze your glutes and brace your abs so your ribs don't flare — this is the base the press works from.",
      "Press straight overhead, moving your head slightly back out of the path if using a bar.",
      "Finish with the weights over the middle of your feet, biceps near your ears, elbows locked.",
      "Lower under control to shoulder height, letting the weights settle before the next rep.",
    ],
    cues: [
      "Leaning back to get the weight up turns it into an incline press and loads your lower back. If the lean appears, the weight is too heavy.",
      "Finish with the weight over your ears, not in front of your face — a press that ends forward keeps the shoulder loaded all set.",
      "Full overhead range only if you can reach it without arching. If not, press to just short of lockout and work on shoulder mobility.",
    ],
  },
  {
    name: "Dumbbell row",
    schools: [],
    category: "pull",
    equipment: "One dumbbell and a bench",
    bodyweight: false,
    level: "Beginner",
    focus: "Lats, mid-back, rear delts, biceps",
    prescription: "3 sets × 8-12 reps per side",
    why:
      "The horizontal pull that balances all the pressing. Supporting yourself on a bench takes the lower back out of the equation, so the back muscles get the work instead of the spinal erectors.",
    steps: [
      "Put your left knee and left hand on a bench, right foot on the floor a little behind you, so your torso is roughly parallel to the ground.",
      "Hold the dumbbell in your right hand, arm hanging straight down, shoulder blade relaxed toward the floor.",
      "Start the pull by drawing the shoulder blade back and down, then pull the dumbbell toward your hip.",
      "Bring your elbow past your ribs, keeping it fairly close to your body. Pause for a beat at the top.",
      "Lower all the way until your arm is straight and you feel the lat stretch, then repeat. Switch sides.",
    ],
    cues: [
      "If your torso rotates open to finish the rep, the weight is too heavy — the shoulders stay square to the floor.",
      "Pull to the hip, not to the armpit. Rowing high turns it into a rear-delt exercise.",
      "Let the arm fully straighten at the bottom. Cutting the stretch out costs you most of the exercise.",
    ],
  },
  {
    name: "Inverted row",
    schools: ["metcon"],
    category: "pull",
    equipment: "A bar or rings at hip height",
    bodyweight: true,
    level: "Beginner",
    focus: "Lats, mid-back, rear delts, trunk",
    prescription: "3 sets × 8-15 reps",
    why:
      "The pulling counterpart to the push-up, and the best bodyweight pull most people can actually do for reps. Change the difficulty by walking your feet in or out — no equipment change needed.",
    steps: [
      "Set a bar at about hip height. Lie underneath it and grip slightly wider than your shoulders, palms facing away.",
      "Extend your legs, heels on the floor, and squeeze your glutes so your body is a straight rigid line.",
      "Pull your shoulder blades together first, then pull your chest to the bar.",
      "Touch the bar (or come as close as you can) with your body still in one line, then lower under control to straight arms.",
    ],
    cues: [
      "Hips sagging is the tell that the trunk gave up. Bend your knees and put your feet flat to make it easier rather than losing the line.",
      "More horizontal is harder, more upright is easier. Walk your feet forward to progress.",
      "Lead with the chest, not the chin.",
    ],
  },
  {
    name: "Pull-up or lat pulldown",
    schools: ["metcon"],
    category: "pull",
    equipment: "A pull-up bar, or a cable pulldown",
    bodyweight: true,
    level: "Advanced",
    focus: "Lats, biceps, mid-back",
    prescription: "3 sets × 4-10 reps",
    why:
      "The vertical pull. If you can't do full reps yet, the pulldown is the same movement with adjustable load — and band-assisted or slow lowering-only reps get you to the first unassisted one faster than waiting does.",
    steps: [
      "Grip the bar slightly wider than shoulder-width, palms facing away. Hang with arms straight.",
      "Before you bend your arms, pull your shoulder blades down — as if putting them into your back pockets.",
      "Pull your elbows down toward your ribs until your chin clears the bar.",
      "Keep your body quiet: brace your abs and squeeze your legs together to stop the swing.",
      "Lower all the way to straight arms, under control, before the next rep.",
    ],
    cues: [
      "Kipping and swinging move your bodyweight without training your back. If you need them, use assistance instead.",
      "Shrugging up into your ears means the lats never engaged — reset the shoulder blades before each pull.",
      "For lowering-only reps: jump or step to the top, then take 5 slow seconds to descend. Three to five of those is a set.",
    ],
  },
  {
    name: "Face pull",
    schools: [],
    category: "pull",
    equipment: "A band or a cable machine",
    bodyweight: false,
    level: "Beginner",
    focus: "Rear delts, rotator cuff, mid-traps",
    prescription: "2-3 sets × 12-20 reps",
    why:
      "Small, unglamorous, and the single best insurance policy against the rounded-shoulder position that pressing and desk work both encourage. Cheap enough to add to the end of any session.",
    steps: [
      "Anchor a band or set a cable at roughly face height. Take one end in each hand, palms facing each other.",
      "Step back until there's tension with your arms straight out in front.",
      "Pull the handles toward your forehead, splitting your hands apart as they arrive.",
      "Finish with your elbows high and slightly behind your shoulders, hands beside your ears, thumbs pointing back.",
      "Hold for a beat, then return slowly to straight arms.",
    ],
    cues: [
      "Light load, high reps. Anything heavy enough to make you lean back is too heavy.",
      "Elbows stay at or above shoulder height for the whole rep.",
      "Pull to the face, not to the chest — pulling low makes it a row.",
    ],
  },
  {
    name: "Dead bug",
    schools: [],
    category: "core",
    equipment: "None",
    bodyweight: true,
    level: "Beginner",
    focus: "Deep abdominals, anti-extension",
    prescription: "3 sets × 6-10 reps per side",
    why:
      "Trains the abs to do their actual job — stopping the spine from moving while the limbs do. Far more transferable than a crunch, and kind to backs that don't enjoy flexion work.",
    steps: [
      "Lie on your back, arms straight up over your shoulders, hips and knees bent to 90° so your shins are parallel to the floor.",
      "Press your lower back gently into the floor and keep it there — that contact is the whole exercise.",
      "Breathe out slowly as you lower your right arm overhead and straighten your left leg toward the floor.",
      "Go only as far as you can without the lower back lifting. Pause just short of the floor.",
      "Return to the start under control and repeat on the other side. That's one rep per side.",
    ],
    cues: [
      "The moment your back arches off the floor, you've exceeded your range — shorten it and keep the contact.",
      "Slow beats big. Three seconds out, three seconds back.",
      "Breathe out on the way out; holding your breath hides the failure rather than preventing it.",
    ],
  },
  {
    name: "Plank",
    schools: [],
    category: "core",
    equipment: "None",
    bodyweight: true,
    level: "Beginner",
    focus: "Whole trunk, shoulders, glutes",
    prescription: "3 sets × 20-45 seconds",
    why:
      "A hard 30-second plank beats a soft three-minute one every time. Once you can hold a genuinely braced position for 45 seconds, progress by adding load or moving to single-arm variations, not by adding minutes.",
    steps: [
      "Set your forearms on the floor, elbows directly under your shoulders, hands either flat or clasped.",
      "Extend your legs behind you, feet hip-width, and come up onto your toes.",
      "Squeeze your glutes hard and tuck your pelvis slightly so your lower back flattens.",
      "Push the floor away with your forearms so your upper back rounds a little rather than sagging between the shoulder blades.",
      "Breathe normally throughout, and stop the set when the position degrades — not when the clock says so.",
    ],
    cues: [
      "Hips high is resting; hips low is your lower back doing the work. Aim for one straight line from ears to heels.",
      "Look at the floor just in front of your hands to keep your neck neutral.",
      "If you can hold it for two minutes, you're not planking hard enough — brace harder or add a variation.",
    ],
  },
  {
    name: "Pallof press",
    schools: ["fascia"],
    category: "core",
    equipment: "A band or a cable machine",
    bodyweight: false,
    level: "Beginner",
    focus: "Obliques, anti-rotation",
    prescription: "3 sets × 8-12 reps per side",
    why:
      "The rotation you resist, rather than the rotation you produce. It trains the trunk to stay square under a sideways pull — the same job it has when you carry a bag in one hand or press with one arm.",
    steps: [
      "Anchor a band at chest height. Stand side-on to it and hold the end in both hands at your sternum.",
      "Step away until the band is taut, feet shoulder-width, knees soft, hips and shoulders square to the front.",
      "Brace, then press your hands straight out in front of your chest.",
      "The band will try to twist you toward the anchor. Resist it — nothing but your arms should move.",
      "Hold the extended position for 2-3 seconds, return to the sternum, then finish the reps and turn around.",
    ],
    cues: [
      "If your torso rotates, step closer to the anchor to reduce the load.",
      "Keep your hands on the centreline of your chest, not drifting toward the anchor side.",
      "Ribs down, glutes on. Standing tall is part of the rep.",
    ],
  },
  {
    name: "Farmer's carry",
    schools: ["kettlebell"],
    category: "core",
    equipment: "Two heavy dumbbells or kettlebells",
    bodyweight: false,
    level: "Beginner",
    focus: "Grip, traps, trunk, whole-body work capacity",
    prescription: "3 sets × 30-40 metres",
    why:
      "Pick up something heavy, walk with it, put it down. Trains grip, posture and trunk stiffness at once, and doubles as conditioning — heart rate climbs fast for something that looks like nothing.",
    steps: [
      "Set the weights beside your feet. Hinge at the hips, grip both handles, and stand up with a flat back.",
      "Stand tall: shoulders back and down, ribs stacked over your pelvis, arms hanging straight.",
      "Walk in a straight line with normal-length, deliberate steps.",
      "Keep breathing — short, steady breaths rather than one long held one.",
      "At the end of the distance, hinge and set the weights down under control instead of dropping them.",
    ],
    cues: [
      "Leaning back or shrugging up means the load has beaten your posture. Lighter weight, better line.",
      "Don't rush. This is a carry, not a race.",
      "When grip fails first, that's still a useful set — add straps only once grip work is no longer the point.",
    ],
  },

  /* --- Starting Strength: the barbell lifts, Rippetoe-style ------------- */
  {
    name: "Low-bar back squat",
    schools: ["strength"],
    category: "lower",
    equipment: "Barbell and a rack",
    bodyweight: false,
    level: "Intermediate",
    focus: "Quads, glutes, adductors, hamstrings, whole posterior chain",
    prescription: "3 sets × 5 reps",
    why:
      "Rippetoe's central lift, and the argument for it is mechanical: the bar sits lower on the back, which puts the hips further behind the bar and recruits more posterior chain than a high-bar squat. It moves the most weight through the longest effective range, which is why it anchors the program.",
    steps: [
      "Set the bar in the rack at about mid-chest height. Grip it narrow, squeeze your shoulder blades together, and set the bar on the shelf of muscle across your rear delts — below the bony top of the shoulder blades.",
      "Get under it, elbows lifted behind you to lock the bar in place, then stand it out of the rack and take two steps back.",
      "Stance a bit wider than shoulder-width, toes out about 30°.",
      "Take a big breath, hold it, and start by sending your hips back and down at the same time.",
      "Keep your back angle more inclined than a high-bar squat, eyes on a spot on the floor a couple of metres ahead.",
      "Descend until the crease of your hip drops below the top of your kneecap — depth is a position, not a feeling.",
      "Drive your hips straight up out of the bottom, keeping the bar over the middle of your feet the whole way, and breathe out at the top.",
    ],
    cues: [
      "The bar path is a vertical line over mid-foot. Any rep where it drifts forward is a rep your back has to pay for.",
      "Knees out, shoved against the elbows at the bottom, keeps the hips open enough to reach depth.",
      "Rising hips with a stalled chest turns the squat into a good morning. Chest and hips leave the bottom together.",
      "Learn this with an empty bar and a coach or a video camera before it gets heavy.",
    ],
  },
  {
    name: "Barbell deadlift",
    schools: ["strength"],
    category: "lower",
    equipment: "Barbell and plates",
    bodyweight: false,
    level: "Intermediate",
    focus: "Whole posterior chain, grip, trunk",
    prescription: "1 set × 5 reps, heavy, after the squat",
    why:
      "The most weight you will ever move, and one hard set of five is usually the whole prescription — the deadlift takes more out of you than it appears to. Every rep starts from a dead stop, so there's no elastic bounce to hide a bad starting position.",
    steps: [
      "Set the bar over the middle of your feet, about 2cm from your shins. Stance is narrow — hip width, toes slightly out.",
      "Bend down and take a grip just outside your legs without moving the bar.",
      "Drop your shins forward until they touch the bar, then lift your chest to set your back flat and hard.",
      "Take the slack out of the bar — pull up on it until you hear or feel the plates settle — then push the floor away.",
      "Keep the bar dragging up your legs, hips and shoulders rising together, until you stand tall with locked hips and knees.",
      "Return it by hinging back: push your hips back first, then bend your knees once the bar clears them. Reset every rep.",
    ],
    cues: [
      "If your back rounds, the set is over. Strip weight and rebuild the position.",
      "Don't lean back or shrug at the top. Standing straight up is lockout.",
      "Hips too low turns it into a squat with a bar in your hands; hips too high makes it a stiff-legged pull. The right height is where your shoulders sit just in front of the bar.",
      "Mixed grip or straps once grip is the limiter — the rest of you can pull more than your fingers can hold.",
    ],
  },
  {
    name: "Barbell bench press",
    schools: ["strength"],
    category: "push",
    equipment: "Barbell, bench and a rack",
    bodyweight: false,
    level: "Intermediate",
    focus: "Chest, triceps, front delts",
    prescription: "3 sets × 5 reps",
    why:
      "The barbell version of the horizontal press: more total load than dumbbells, at the cost of a fixed hand path. In a linear-progression program it alternates with the overhead press session to session.",
    steps: [
      "Lie down so your eyes are directly under the bar. Grip it so your forearms will be vertical at the bottom — usually a thumb's length outside shoulder width.",
      "Plant your feet, arch your upper back slightly, and pull your shoulder blades together and down into the bench.",
      "Unrack to a position over your shoulders with straight arms, then move the bar forward over your lower chest.",
      "Take a breath, hold it, and lower the bar under control to touch your chest around the base of the sternum.",
      "Press back up and slightly back toward your shoulders, finishing over the same point you started.",
      "Breathe at the top between reps. Use a spotter, or a rack with safety pins set at chest height, for anything heavy.",
    ],
    cues: [
      "Elbows about 45° from your torso — neither pinned to your ribs nor flared to a T.",
      "Feet drive into the floor and the hips stay on the bench. Bridging your hips up is a different lift.",
      "Never bench a heavy set over an open collar with no spotter and no safeties.",
    ],
  },
  {
    name: "Power clean",
    schools: ["strength", "metcon"],
    category: "power",
    equipment: "Barbell and bumper plates",
    bodyweight: false,
    level: "Advanced",
    focus: "Rate of force development, posterior chain, whole-body coordination",
    prescription: "5 sets × 3 reps, technique first",
    why:
      "The lift that trains how fast you can produce force, not just how much. Rippetoe includes it because strength expressed slowly is only half the picture, and because a power clean cannot be grinded — either the bar moves fast enough to rack, or the rep doesn't happen.",
    steps: [
      "Set up like a deadlift, with the bar over mid-foot and a grip just outside your legs.",
      "Pull the bar off the floor at a controlled speed, keeping your back angle constant until the bar passes your knees.",
      "As the bar reaches mid-thigh, jump: extend the hips and knees violently and shrug.",
      "Pull yourself under the bar, whipping your elbows around and up.",
      "Catch it on the front of your shoulders in a quarter squat, elbows high, then stand up.",
      "Lower it back to the floor under control (or drop it, with bumper plates on a platform) and reset each rep.",
    ],
    cues: [
      "Speed is the point. If it's slow enough to grind into the rack position, it's too heavy.",
      "Curling the bar up with your arms is the most common error — the arms stay long until the hips have finished.",
      "This is a coached lift. Learn it light, with someone watching, before it becomes a conditioning movement.",
    ],
  },

  /* --- Hardstyle kettlebell: Pavel's minimum effective dose ------------- */
  {
    name: "Kettlebell swing (hardstyle)",
    schools: ["kettlebell", "metcon", "fascia"],
    category: "power",
    equipment: "One kettlebell",
    bodyweight: false,
    level: "Beginner",
    focus: "Hip power, glutes, hamstrings, trunk, conditioning",
    prescription: "10 sets × 10 reps, on the minute",
    why:
      "Pavel's signature movement and half of the Simple & Sinister program. It's a ballistic hinge — the hips throw the bell, the arms only steer — which trains explosive hip extension and a serious heart rate from a single piece of equipment.",
    steps: [
      "Set the bell about a foot in front of you. Hinge, reach for the handle with both hands, and tilt it back toward you.",
      "With a flat back and locked-in lats, hike the bell back between your legs like a rugby pass — above the knees, not below.",
      "Snap your hips forward hard and stand up sharply. The bell floats up to about chest height on its own.",
      "At the top, everything is rigid for an instant: glutes clenched, abs braced, knees locked, exhale sharp through the teeth.",
      "Let the bell fall, wait for it, and only hinge once it's back close to your body. Load the hips and repeat.",
      "Finish the set by guiding the bell down in front of you and setting it back on the floor with a hinge.",
    ],
    cues: [
      "It's a hinge, not a squat, and not a front raise. If your arms are lifting the bell, the hips didn't finish.",
      "The top is a standing plank. No leaning back, no shrugging.",
      "Breathe with the movement: sharp exhale at the top, inhale as the bell falls.",
      "Hardstyle stops at chest height. Overhead is a different (American) swing with different demands on the shoulder.",
    ],
  },
  {
    name: "Turkish get-up",
    schools: ["kettlebell", "fascia"],
    category: "core",
    equipment: "One kettlebell",
    bodyweight: false,
    level: "Intermediate",
    focus: "Shoulder stability, trunk, hips, whole-body coordination",
    prescription: "5 reps per side, slow — a practice, not a set",
    why:
      "The other half of Simple & Sinister. Stand up from the floor with a weight locked out overhead, then reverse it. It's a mobility screen, a shoulder-stability drill and a trunk exercise in one, and it exposes exactly which link in the chain is weak.",
    steps: [
      "Lie on your side, curl around the bell with both hands, then roll onto your back and press it up with one arm.",
      "Same-side knee bent, foot flat. Opposite arm and leg out at about 45°. Eyes stay on the bell.",
      "Roll onto the free elbow, then push up onto that hand — sit tall.",
      "Bridge your hips high, then thread the straight leg back underneath you into a half-kneeling position.",
      "Windshield-wiper the back shin into line, torso upright, and stand up out of the lunge.",
      "Reverse the whole sequence step by step to return to the floor, then switch sides.",
    ],
    cues: [
      "Learn it with a shoe balanced on your fist before you use a bell. If the shoe falls, the shoulder isn't stacked.",
      "The loaded arm stays locked and vertical throughout, shoulder packed down away from the ear.",
      "Slow is the point. A single rep should take 30 seconds or more.",
    ],
  },
  {
    name: "Kettlebell clean & press",
    schools: ["kettlebell"],
    category: "push",
    equipment: "One kettlebell",
    bodyweight: false,
    level: "Intermediate",
    focus: "Shoulders, upper back, hips, trunk",
    prescription: "5 sets × 5 reps per side, or ladders of 1-2-3",
    why:
      "Get the bell to the shoulder with the hips, then press it overhead with total-body tension. Pavel's programs often build entire strength blocks around this one movement, done frequently and never to failure.",
    steps: [
      "Start with the bell between your feet. Hinge and hike it back with one hand.",
      "Snap your hips and, as the bell rises, keep it close and 'tame the arc' — pull your elbow to your ribs and let the bell roll around your wrist rather than flipping over onto it.",
      "Catch it in the rack position: forearm vertical against your torso, elbow tucked, wrist straight, bell resting in the crook of your arm.",
      "Brace everything — glutes, abs, the opposite fist — and press it straight overhead, finishing with the arm by your ear.",
      "Lower under control back to the rack, then hinge and set it down (or clean the next rep).",
    ],
    cues: [
      "A banging clean means the arc was too wide. Keep the bell close and the elbow low.",
      "Wrist straight in the rack and at lockout. A bent-back wrist is where the ache comes from.",
      "Press with the whole body: squeeze the glutes and the free hand and the bell gets lighter.",
    ],
  },

  /* --- Box conditioning: the metcon staples ----------------------------- */
  {
    name: "Burpee",
    schools: ["metcon"],
    category: "cardio",
    equipment: "None",
    bodyweight: true,
    level: "Beginner",
    focus: "Whole body, work capacity",
    prescription: "AMRAP or EMOM formats — e.g. 10 per minute × 8 min",
    why:
      "The purest conditioning movement in the box vocabulary: no equipment, no skill ceiling, and an unmatched heart-rate cost per rep. Also the movement most likely to be done sloppily at rep forty, which is where pacing becomes the skill.",
    steps: [
      "From standing, squat down and place both hands on the floor in front of your feet.",
      "Jump or step your feet back into a plank, keeping your body in one line.",
      "Lower your chest and thighs to the floor.",
      "Push back up, jump or step your feet back under your hips.",
      "Stand and jump, clapping your hands overhead — that's one rep.",
    ],
    cues: [
      "Step back and step in is a legitimate scale, not a lesser rep. It keeps the spine safer at high volume.",
      "Pace from the first minute. Everyone can do the first twenty; the score is decided by the last twenty.",
      "Keep the trunk braced on the way down — flopping onto the floor is a rounded-back rep repeated a hundred times.",
    ],
  },
  {
    name: "Wall ball",
    schools: ["metcon"],
    category: "power",
    equipment: "Medicine ball and a wall target",
    bodyweight: false,
    level: "Beginner",
    focus: "Quads, glutes, shoulders, aerobic capacity",
    prescription: "Sets of 15-20 inside a conditioning piece",
    why:
      "A front squat and a push press stitched together with a target, which is what makes it brutal: there's no rest position, and the ball dictates the tempo. A staple of box workouts precisely because it scales cleanly by ball weight and target height.",
    steps: [
      "Stand about an arm's length from the wall, holding the ball at your chest, elbows in.",
      "Squat to at least parallel, keeping the ball close and your chest up.",
      "Drive up out of the bottom and use that momentum to throw the ball to a target — typically 9-10 feet up the wall.",
      "Catch the ball as it comes down, absorbing it into the next squat in one continuous movement.",
    ],
    cues: [
      "Depth first. Under fatigue, the squat is what shortens — the throw usually survives.",
      "Let the legs throw the ball. Arms-only reps burn the shoulders out in half the set.",
      "Catch it high and ride it down, rather than letting it drop onto locked arms.",
    ],
  },
  {
    name: "Double-unders",
    schools: ["metcon", "fascia"],
    category: "cardio",
    equipment: "A speed rope",
    bodyweight: true,
    level: "Intermediate",
    focus: "Calves, Achilles elasticity, coordination, conditioning",
    prescription: "Sets of 20-50 inside a conditioning piece",
    why:
      "Two rope passes per jump. Beyond the conditioning, it's an elastic drill: short ground contacts and a stiff, springy ankle are exactly the qualities fascial training is after, which is why skipping shows up in both traditions.",
    steps: [
      "Size the rope: standing on the middle, the handles should reach roughly your armpits.",
      "Hold the handles slightly in front of your hips, elbows close to your ribs.",
      "Jump with a stiff, quiet ankle — a small pogo bounce, not a tuck jump.",
      "Spin the rope from the wrists, fast, so it passes twice per jump.",
      "Build in sets: 5 clean doubles, rest, repeat. Stringing 50 sloppy ones together teaches the wrong pattern.",
    ],
    cues: [
      "Bending the knees to buy air time is the most common fault — the height comes from the ankles.",
      "Big arm circles slow the rope. Keep the elbows in and let the wrists do it.",
      "Single-unders at speed are the right progression while the timing comes together.",
    ],
  },

  /* --- Fascial elasticity: springs, long levers, tissue ----------------- */
  {
    name: "Pogo hops",
    schools: ["fascia", "metcon"],
    category: "power",
    equipment: "None",
    bodyweight: true,
    level: "Beginner",
    focus: "Achilles and plantar fascia stiffness, elastic rebound",
    prescription: "3-5 sets × 15-20 contacts, fresh, before lifting",
    why:
      "The simplest expression of the fascial-elasticity idea: store energy on landing and give it straight back, with the muscle barely changing length. Tendon and fascia handle the spring — training it is what makes running and jumping feel cheap rather than laborious.",
    steps: [
      "Stand tall, feet hip-width, arms relaxed at your sides or on your hips.",
      "Bounce on the balls of your feet with knees almost straight, using only the ankles.",
      "Aim for the shortest possible ground contact — think of the floor as hot.",
      "Keep the rhythm even and quiet; 15-20 contacts is a set.",
      "Progress by adding height, then by hopping on one leg, only once the rhythm is clean.",
    ],
    cues: [
      "Quiet landings. Noise is energy you absorbed instead of returned.",
      "Knees stay long — as soon as they bend deeply, the muscles take over from the springs.",
      "Do these fresh, not at the end of a session. Elastic work is a quality, not a finisher.",
    ],
  },
  {
    name: "Rotational medicine-ball throw",
    schools: ["fascia"],
    category: "power",
    equipment: "A medicine ball and a solid wall",
    bodyweight: false,
    level: "Beginner",
    focus: "Obliques, hips, the diagonal sling from hip to opposite shoulder",
    prescription: "3 sets × 6-8 throws per side",
    why:
      "Most training happens in one plane; almost nothing you do outside the gym does. A rotational throw loads the diagonal myofascial sling from one hip to the opposite shoulder as a spring — wind up, then let it snap back — which is the mechanism fascial work is actually about.",
    steps: [
      "Stand side-on to a wall, about two metres away, ball held at chest height.",
      "Set your feet parallel, knees soft, weight even.",
      "Wind up by rotating your torso and hips away from the wall, letting the back heel turn up.",
      "Reverse it fast: drive the back hip through, rotate, and throw the ball into the wall as hard as you can.",
      "Catch or collect the rebound, reset your stance completely, and repeat. Switch sides after the set.",
    ],
    cues: [
      "Power comes from the hip, not the arms. If your shoulders lead, you'll feel it in your lower back.",
      "Every rep is maximal. Six hard throws beat twenty moderate ones — this is a power drill, not conditioning.",
      "Let the back foot pivot. Pinning it down puts the twist in your knee instead of your hip.",
    ],
  },
  {
    name: "360° lunge matrix",
    schools: ["fascia"],
    category: "mobility",
    equipment: "None",
    bodyweight: true,
    level: "Beginner",
    focus: "Hips, adductors, ankles, multi-directional tissue loading",
    prescription: "2 rounds × 4 directions per leg, as a warm-up",
    why:
      "One leg, four directions: forward, diagonal, lateral, and rotational-backward. Fascial tissue is organised in continuous multi-directional sheets, and loading it in only one plane leaves most of it untrained — this covers the compass in about ninety seconds.",
    steps: [
      "Start standing tall, hands free.",
      "Lunge straight forward with the right leg, touch down softly, and push back to the start.",
      "Lunge forward and out at 45° with the same leg, return.",
      "Step directly sideways into a lateral lunge — right knee bends, left leg stays straight — return.",
      "Step back and across behind you into a curtsy-style rotational lunge, return.",
      "That's one round on the right. Repeat on the left.",
    ],
    cues: [
      "Control the landing in every direction. This is tissue loading, not a speed drill.",
      "Keep the torso tall and let the hip do the reaching.",
      "Reduce the range in any direction that pinches. The matrix is a map, not a test.",
    ],
  },
  {
    name: "Self-myofascial release",
    schools: ["fascia"],
    category: "mobility",
    equipment: "Foam roller or a lacrosse ball",
    bodyweight: true,
    level: "Beginner",
    focus: "Tissue glide, short-term range of motion, sensation",
    prescription: "5-10 min, most days, or before training",
    why:
      "The honest version: rolling reliably increases range of motion for a while and usually feels good, and the current best explanation is neural — changing how the tissue is sensed — rather than physically breaking anything down. Useful as a warm-up and a habit, not as a structural fix.",
    steps: [
      "Pick one area — calves, quads, glutes, lats, upper back.",
      "Rest the area on the roller and support some of your bodyweight with your hands or the other leg.",
      "Roll slowly, about 2-3cm per second, breathing normally.",
      "When you find a tender spot, stop and hold for 20-30 seconds, letting your breath settle rather than tensing against it.",
      "Follow it with the range of motion you were after — a few slow reps of the movement, so the new range gets used.",
    ],
    cues: [
      "Pain that makes you hold your breath is too much. The tissue can't relax while you're bracing against it.",
      "Never roll directly on a joint, a bone, or the front of the lower back.",
      "The effect is short-lived, which is why it belongs before training rather than instead of it.",
    ],
  },
  {
    name: "Zone 2 walk, ride or row",
    schools: [],
    category: "cardio",
    equipment: "None, or any cardio machine",
    bodyweight: true,
    level: "Beginner",
    focus: "Aerobic base, mitochondrial density, fat oxidation",
    prescription: "2-4 sessions × 30-60 minutes weekly",
    why:
      "The unglamorous majority of your cardio. Sustained easy work builds mitochondrial density and capillary supply in muscle — the machinery that clears both fat and glucose — and it recovers fast enough not to interfere with lifting.",
    steps: [
      "Pick anything continuous: brisk walking on a slight incline, easy cycling, rowing, or a slow jog.",
      "Build up over 5 minutes until your breathing is noticeably deeper but still comfortable.",
      "Hold an intensity where you could speak a full sentence but wouldn't want to hold a conversation — roughly 60-70% of max heart rate.",
      "Stay there for 30-60 minutes, resisting the urge to drift faster as you warm up.",
      "Finish with 3-5 easy minutes rather than stopping abruptly.",
    ],
    cues: [
      "If you're gasping between words, you're in Zone 3 — slow down, even if it feels too easy to count.",
      "Walking uphill gets most people into Zone 2 more reliably than jogging, which usually overshoots it.",
      "Duration is the variable that matters here. Add minutes, not speed.",
    ],
  },
  {
    name: "Post-meal walk",
    schools: [],
    category: "cardio",
    equipment: "None",
    bodyweight: true,
    level: "Beginner",
    focus: "Acute glucose disposal",
    prescription: "10-15 minutes, after your largest meals",
    why:
      "The highest-yield ten minutes in this whole library. Contracting muscle pulls glucose out of the bloodstream without needing insulin, and doing it while the meal is still being absorbed blunts the peak rather than cleaning up after it.",
    steps: [
      "Start within about 15-30 minutes of finishing the meal — the earlier the better.",
      "Walk at an easy, conversational pace. This is not a workout and shouldn't feel like one.",
      "Ten minutes is the useful minimum; 15-20 is better if the meal was carb-heavy.",
      "Keep it flat and unhurried — the goal is contracting muscle, not elevated heart rate.",
    ],
    cues: [
      "Consistency beats intensity here. A daily ten minutes outperforms an occasional hour.",
      "Stairs, a lap of the block, or pacing on a phone call all count.",
      "It stacks with everything else on this page — it isn't a substitute for a training session.",
    ],
  },
  {
    name: "Bike intervals",
    schools: ["metcon"],
    category: "cardio",
    equipment: "A stationary bike (or any machine you can go hard on safely)",
    bodyweight: false,
    level: "Intermediate",
    focus: "VO₂ max, high-end aerobic power",
    prescription: "1 session × 6-8 rounds weekly",
    why:
      "The small, hard slice. Short high-intensity intervals raise the ceiling of your aerobic system in a way that easy work doesn't, and a bike lets you reach real intensity with almost no eccentric load — so it doesn't wreck your lifting days.",
    steps: [
      "Warm up for 8-10 minutes of easy pedalling, with two or three 20-second pickups near the end.",
      "Go hard for 30 seconds — around 85-95% of max heart rate, an effort you could not hold for three minutes.",
      "Spin easy for 2 minutes. The recovery is part of the interval, not an intermission.",
      "Repeat for 6-8 rounds, aiming for consistent output rather than a heroic first round.",
      "Cool down for 5-10 minutes of easy pedalling.",
    ],
    cues: [
      "If round six is dramatically weaker than round one, you started too hard. Even pacing is the skill.",
      "Once a week is plenty alongside three lifting days. Two is the ceiling for most people.",
      "Don't put this the day before a heavy lower-body session.",
    ],
  },
];
